<a href="https://colab.research.google.com/github/bybbaa/MN/blob/main/%D0%9B%D0%A0_1_%D0%9D%D0%B0%D1%86%D0%B8%D0%BA_4_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Нацик 4-8 (була присутня)

In [ ]:
import numpy as np
np.__version__

'2.0.2'

In [ ]:
matrix = np.random.randint(1,6, size=(3, 3))

matrix

array([[2, 5, 1],
       [3, 4, 2],
       [2, 3, 3]])

In [ ]:
det = np.linalg.det(matrix)
det

np.float64(-12.000000000000005)

In [ ]:
pr = np.prod(matrix)
pr

np.int64(4320)

In [ ]:
prod_1 = np.prod(matrix[0])
prod_2 = np.prod(matrix[1])
prod_3 = np.prod(matrix[2])
prod_1*prod_2*prod_3

np.int64(4320)

In [ ]:
sum_1 = np.sum(matrix)
sum_1

np.int64(25)

In [ ]:
np.max(matrix)

np.int64(5)

In [ ]:
np.min(matrix)

np.int64(1)

In [ ]:
np.mean(matrix)

np.float64(2.7777777777777777)

In [ ]:
np.sqrt(matrix)

array([[1.41421356, 2.23606798, 1.        ],
       [1.73205081, 2.        , 1.41421356],
       [1.41421356, 1.73205081, 1.73205081]])

In [ ]:
np.sum(matrix, axis=1).reshape(-1, 1)

array([[8],
       [9],
       [8]])

In [ ]:
vector = np.random.randint(0, 10, size=25)
print("Початковий вектор:")
print(vector)

sorted_vector = np.sort(vector)[::-1]
print("Вектор після сортування за спаданням:")
print(sorted_vector)

Початковий вектор:
[0 2 7 2 6 2 0 9 7 7 5 8 9 7 9 3 2 9 3 0 2 2 3 3 1]
Вектор після сортування за спаданням:
[9 9 9 9 8 7 7 7 7 6 5 3 3 3 3 2 2 2 2 2 2 1 0 0 0]


In [ ]:
from scipy import stats
stats.mode(vector)

ModeResult(mode=np.int64(9), count=np.int64(7))

In [ ]:
np.median(vector)

np.float64(5.0)

In [ ]:
np.mean(vector)

np.float64(5.48)

In [ ]:
np.max(vector)

np.int64(9)

In [ ]:
np.min(vector)

np.int64(0)

In [ ]:
m1 = np.random.randint(1, 11, size=(4, 4))
m1

array([[ 3,  4,  8,  8],
       [10,  9,  8,  2],
       [ 8,  5,  1,  5],
       [ 9,  6,  8, 10]])

In [ ]:
m2 = np.random.randint(1, 11, size=(4, 4))
m2

array([[ 3,  9,  1,  8],
       [ 5, 10,  3,  6],
       [ 3,  4,  7, 10],
       [10,  9,  9, 10]])

In [ ]:
m1 + m2

array([[ 6, 13,  9, 16],
       [15, 19, 11,  8],
       [11,  9,  8, 15],
       [19, 15, 17, 20]])

In [ ]:
m1 - m2

array([[ 0, -5,  7,  0],
       [ 5, -1,  5, -4],
       [ 5,  1, -6, -5],
       [-1, -3, -1,  0]])

In [ ]:
m1 * m2

array([[  9,  36,   8,  64],
       [ 50,  90,  24,  12],
       [ 24,  20,   7,  50],
       [ 90,  54,  72, 100]])

In [ ]:
np.dot(m1, m2)

array([[133, 171, 143, 208],
       [119, 230, 111, 234],
       [102, 171,  75, 154],
       [181, 263, 173, 288]])

In [ ]:
np.divide(m1, m2, where=(m2!=0))

array([[1.        , 0.44444444, 8.        , 1.        ],
       [2.        , 0.9       , 2.66666667, 0.33333333],
       [2.66666667, 1.25      , 0.14285714, 0.5       ],
       [0.9       , 0.66666667, 0.88888889, 1.        ]])

In [ ]:
m1 / m2

array([[1.        , 0.44444444, 8.        , 1.        ],
       [2.        , 0.9       , 2.66666667, 0.33333333],
       [2.66666667, 1.25      , 0.14285714, 0.5       ],
       [0.9       , 0.66666667, 0.88888889, 1.        ]])

In [ ]:
x = np.arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [ ]:
x1 = x.reshape((3, 3))
x1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [ ]:
x1 = np.arange(6)
x1

array([0, 1, 2, 3, 4, 5])

In [ ]:
x2 = np.arange(3.0)
x2

array([0., 1., 2.])

In [ ]:
np.multiply(x1, x2)

array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])

In [ ]:
np.power(x1, 3)

array([  0,   1,   8,  27,  64, 125])

In [ ]:
x2 = np.array([1, 2, 3, 3, 5, 1])
x1 = np.arange(6)
x1 ** x2

array([   0,    1,    8,   27, 1024,    5])

In [ ]:
vector = np.array ([1, 2, 3, 4, 5])
vector

array([1, 2, 3, 4, 5])

In [ ]:
v1 = np.matrix([1, 2, 3, 4, 5])
v1

matrix([[1, 2, 3, 4, 5]])

In [ ]:
v2 = v1.T
v2

matrix([[1],
        [2],
        [3],
        [4],
        [5]])

In [ ]:
v = np.array([1, 2, 3, 4, 5])
v

array([1, 2, 3, 4, 5])

In [ ]:
v[::-1]

array([5, 4, 3, 2, 1])

In [ ]:
v = np.flip(v)
v

array([5, 4, 3, 2, 1])

In [ ]:
np.mean(v)

np.float64(3.0)

In [ ]:
np.max(v)

np.int64(5)

In [ ]:
np.min(v)

np.int64(1)

In [ ]:
v1 = np.array([1, 2, 3])
v1

array([1, 2, 3])

In [ ]:
v2 = np.array([4, 5, 6])
v2

array([4, 5, 6])

In [ ]:
np.dot(v1,v2)

np.int64(32)

In [ ]:
v = np.array([1, 2, 2, 3, 4, 5, 6, 5])

np.unique(v)

array([1, 2, 3, 4, 5, 6])

In [ ]:
vector = np.array([1, 2, 3, 4, 5])
length = np.linalg.norm(vector)

np.isclose(length, 5)

np.False_

In [ ]:
a = np.random.randint(0, 20, (3, 3))
a

array([[19,  5,  7],
       [13,  9,  3],
       [11, 16, 12]])

In [ ]:
np.linalg.det(a)

np.float64(1287.9999999999993)

In [ ]:
np.linalg.inv(a)

array([[ 0.04658385,  0.04037267, -0.03726708],
       [-0.09549689,  0.11723602,  0.02639752],
       [ 0.08462733, -0.19332298,  0.08229814]])

In [ ]:
a = np.array([[2, 3, 7], [1, 4, 0], [-1, 5, 3]])
b = np.array([7, 2, 6])
x = np.linalg.solve(a,b)
print(x)
inv_a = np.linalg.inv(a)
x1 = inv_a.dot(b)
print(x1)

[-0.41025641  0.6025641   0.85897436]
[-0.41025641  0.6025641   0.85897436]
